export const COMPENSATION_BASIS_KEY = 'compensation.basis'
export const COMPENSATION_BPS_KEY = 'compensation.percent_bps'
export const COMPENSATION_TRACKED_OWNER_KEY = 'compensation.tracked_acquisition_owner_user_id'
export const COMPENSATION_TRACKED_OWNER_LABEL = 'Default tracked-acquisition credit owner'
export const COMPENSATION_TRACKED_OWNER_DESCRIPTION
  = 'Prospects attributable to a tracking link generated by this app receive compensation credit for this user. Campaign ownership is operational only and does not assign compensation. Walk-ins and other leads without a generated tracking link stay unassigned unless an administrator assigns them.'
export const COMPENSATION_BASIS_PERCENT_OF_MONTHLY = 'PERCENT_OF_MONTHLY'
export const COMPENSATION_DEFAULT_BPS = 5000

export function compensationAmountCents(monthlyCents: number, basisBps: number) {
  if (!Number.isInteger(monthlyCents) || monthlyCents < 0 || !Number.isInteger(basisBps) || basisBps < 0) {
    return 0
  }
  return Math.round((monthlyCents * basisBps) / 10_000)
}
