const MINUTE = {
  am6: 6 * 60,
  am10: 10 * 60,
  pm12: 12 * 60,
  pm415: 16 * 60 + 15,
  pm5: 17 * 60,
  pm6: 18 * 60,
  pm7: 19 * 60,
  pm730: 19 * 60 + 30,
  am1130: 11 * 60 + 30,
} as const

export const INTRO_RULE_SEED = [
  { seedKey: 'adult-mon-0600-gi', programCode: 'ADULT_BJJ', weekday: 1, startMinute: MINUTE.am6, name: 'Jiu Jitsu with Gi — Adults' },
  { seedKey: 'adult-mon-1800-gi', programCode: 'ADULT_BJJ', weekday: 1, startMinute: MINUTE.pm6, name: 'Jiu Jitsu with Gi — Adults' },
  { seedKey: 'adult-mon-1900-nogi', programCode: 'ADULT_BJJ', weekday: 1, startMinute: MINUTE.pm7, name: 'Jiu Jitsu No-Gi — Adults' },
  { seedKey: 'adult-tue-1200-gi', programCode: 'ADULT_BJJ', weekday: 2, startMinute: MINUTE.pm12, name: 'Jiu Jitsu with Gi — Adults' },
  { seedKey: 'adult-tue-1800-nogi', programCode: 'ADULT_BJJ', weekday: 2, startMinute: MINUTE.pm6, name: 'Jiu Jitsu No-Gi — Adults' },
  { seedKey: 'adult-tue-1900-gi', programCode: 'ADULT_BJJ', weekday: 2, startMinute: MINUTE.pm7, name: 'Jiu Jitsu with Gi — Adults' },
  { seedKey: 'adult-tue-1900-striking', programCode: 'ADULT_BJJ', weekday: 2, startMinute: MINUTE.pm7, name: 'Striking 101 — Adults' },
  { seedKey: 'adult-wed-0600-nogi', programCode: 'ADULT_BJJ', weekday: 3, startMinute: MINUTE.am6, name: 'Jiu Jitsu No-Gi — Adults' },
  { seedKey: 'adult-wed-1800-gi', programCode: 'ADULT_BJJ', weekday: 3, startMinute: MINUTE.pm6, name: 'Jiu Jitsu with Gi — Adults' },
  { seedKey: 'adult-wed-1900-mma', programCode: 'ADULT_BJJ', weekday: 3, startMinute: MINUTE.pm7, name: 'MMA Cross Training — Adults' },
  { seedKey: 'adult-thu-1200-nogi', programCode: 'ADULT_BJJ', weekday: 4, startMinute: MINUTE.pm12, name: 'Jiu Jitsu No-Gi — Adults' },
  { seedKey: 'adult-thu-1800-nogi', programCode: 'ADULT_BJJ', weekday: 4, startMinute: MINUTE.pm6, name: 'Jiu Jitsu No-Gi — Adults' },
  { seedKey: 'adult-thu-1900-gi', programCode: 'ADULT_BJJ', weekday: 4, startMinute: MINUTE.pm7, name: 'Jiu Jitsu with Gi — Adults' },
  { seedKey: 'adult-fri-0600-gi', programCode: 'ADULT_BJJ', weekday: 5, startMinute: MINUTE.am6, name: 'Jiu Jitsu with Gi — Adults' },
  { seedKey: 'adult-fri-1200-open', programCode: 'ADULT_BJJ', weekday: 5, startMinute: MINUTE.pm12, name: 'Open Mat Gi/No-Gi — Adults' },
  { seedKey: 'adult-fri-1800-study', programCode: 'ADULT_BJJ', weekday: 5, startMinute: MINUTE.pm6, endMinute: MINUTE.pm730, name: 'Study Hall (Gi/No-Gi) & Sparring — Adults' },
  { seedKey: 'adult-fri-1900-striking', programCode: 'ADULT_BJJ', weekday: 5, startMinute: MINUTE.pm7, name: 'Striking 101 — Adults' },
  { seedKey: 'adult-sat-1000-study', programCode: 'ADULT_BJJ', weekday: 6, startMinute: MINUTE.am10, endMinute: MINUTE.am1130, name: 'Study Hall (Gi/No-Gi) & Sparring — Adults' },

  { seedKey: 'kids-ninjas-mon-1615-nogi', programCode: 'KIDS_BJJ', weekday: 1, startMinute: MINUTE.pm415, name: 'Ninjas No-Gi', ageMin: 4, ageMax: 7 },
  { seedKey: 'kids-ninjas-tue-1615-bjj', programCode: 'KIDS_BJJ', weekday: 2, startMinute: MINUTE.pm415, name: 'Ninjas BJJ', ageMin: 4, ageMax: 7 },
  { seedKey: 'kids-ninjas-wed-1615-bjj', programCode: 'KIDS_BJJ', weekday: 3, startMinute: MINUTE.pm415, name: 'Ninjas BJJ', ageMin: 4, ageMax: 7 },
  { seedKey: 'kids-ninjas-thu-1615-bjj', programCode: 'KIDS_BJJ', weekday: 4, startMinute: MINUTE.pm415, name: 'Ninjas BJJ', ageMin: 4, ageMax: 7 },
  { seedKey: 'kids-fun-fri-1615', programCode: 'KIDS_BJJ', weekday: 5, startMinute: MINUTE.pm415, name: 'Fun Day — Ninjas & Samurai', ageMin: 4, ageMax: 11 },

  { seedKey: 'kids-samurai-mon-1700-nogi', programCode: 'KIDS_BJJ', weekday: 1, startMinute: MINUTE.pm5, name: 'Samurai No-Gi', ageMin: 8, ageMax: 11 },
  { seedKey: 'kids-samurai-tue-1700-bjj', programCode: 'KIDS_BJJ', weekday: 2, startMinute: MINUTE.pm5, name: 'Samurai BJJ', ageMin: 8, ageMax: 11 },
  { seedKey: 'kids-samurai-wed-1700-bjj', programCode: 'KIDS_BJJ', weekday: 3, startMinute: MINUTE.pm5, name: 'Samurai BJJ', ageMin: 8, ageMax: 11 },
  { seedKey: 'kids-samurai-thu-1700-bjj', programCode: 'KIDS_BJJ', weekday: 4, startMinute: MINUTE.pm5, name: 'Samurai BJJ', ageMin: 8, ageMax: 11 },

  { seedKey: 'kids-future-mon-1700-nogi', programCode: 'KIDS_BJJ', weekday: 1, startMinute: MINUTE.pm5, name: 'Future Champs No-Gi', ageMin: 12, ageMax: 16 },
  { seedKey: 'kids-future-tue-1700-bjj', programCode: 'KIDS_BJJ', weekday: 2, startMinute: MINUTE.pm5, name: 'Future Champs BJJ', ageMin: 12, ageMax: 16 },
  { seedKey: 'kids-future-wed-1700-bjj', programCode: 'KIDS_BJJ', weekday: 3, startMinute: MINUTE.pm5, name: 'Future Champs BJJ', ageMin: 12, ageMax: 16 },
  { seedKey: 'kids-future-thu-1700-nogi', programCode: 'KIDS_BJJ', weekday: 4, startMinute: MINUTE.pm5, name: 'Future Champs No-Gi', ageMin: 12, ageMax: 16 },
  { seedKey: 'kids-future-fri-1700-mma', programCode: 'KIDS_BJJ', weekday: 5, startMinute: MINUTE.pm5, name: 'Future Champs MMA & Self Defense', ageMin: 12, ageMax: 16 },
] as const
